<?php

namespace ESolution\LaravelAccounting\Enums;

enum AccountingServiceCode: string
{
    case SALES_CASH = 'SALES_CASH';
    case SALES_CREDIT = 'SALES_CREDIT';
    case SALES_RETURN = 'SALES_RETURN';
    case SALES_DISCOUNT = 'SALES_DISCOUNT';
    case SALES_WRITE_OFF = 'SALES_WRITE_OFF';

    case PURCHASE_CASH = 'PURCHASE_CASH';
    case PURCHASE_CREDIT = 'PURCHASE_CREDIT';
    case PURCHASE_RETURN = 'PURCHASE_RETURN';

    case STOCK_OPENING = 'STOCK_OPENING';
    case STOCK_ADJUSTMENT_PLUS = 'STOCK_ADJUSTMENT_PLUS';
    case STOCK_ADJUSTMENT_MINUS = 'STOCK_ADJUSTMENT_MINUS';
    case STOCK_TRANSFER = 'STOCK_TRANSFER';
    case STOCK_OPNAME_GAIN = 'STOCK_OPNAME_GAIN';
    case STOCK_OPNAME_LOSS = 'STOCK_OPNAME_LOSS';

    case CASH_IN = 'CASH_IN';
    case CASH_OUT = 'CASH_OUT';
    case BANK_TRANSFER = 'BANK_TRANSFER';
    case JOURNAL_MANUAL = 'JOURNAL_MANUAL';
    case PETTY_CASH = 'PETTY_CASH';

    case EXPENSE = 'EXPENSE';
    case PREPAID_EXPENSE = 'PREPAID_EXPENSE';

    case PAYROLL = 'PAYROLL';
    case PAYROLL_ACCRUAL = 'PAYROLL_ACCRUAL';

    case ASSET_PURCHASE = 'ASSET_PURCHASE';
    case ASSET_DEPRECIATION = 'ASSET_DEPRECIATION';
    case ASSET_DISPOSAL = 'ASSET_DISPOSAL';
    case ASSET_REVALUATION = 'ASSET_REVALUATION';

    case CUSTOMER_RECEIVABLE_PAYMENT = 'CUSTOMER_RECEIVABLE_PAYMENT';
    case CUSTOMER_RECEIVABLE_WRITE_OFF = 'CUSTOMER_RECEIVABLE_WRITE_OFF';

    case VENDOR_PAYMENT = 'VENDOR_PAYMENT';
    case VENDOR_PAYABLE_WRITE_OFF = 'VENDOR_PAYABLE_WRITE_OFF';

    case TAX_OUTPUT = 'TAX_OUTPUT';
    case TAX_INPUT = 'TAX_INPUT';
    case TAX_PAYMENT = 'TAX_PAYMENT';

    case MONTH_END_CLOSING = 'MONTH_END_CLOSING';
    case YEAR_END_CLOSING = 'YEAR_END_CLOSING';
}
